- name: Install Nginx repository
  template: src=nginx.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: Install Nginx plugin Agent
  yum: name=nginx-nr-agent enablerepo=nginx state=present
